name: ci

on: [push, pull_request]

jobs:
  deno:
    name: dax-${{ matrix.os }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'dsherret:')
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Check format
        if: contains(matrix.os, 'ubuntu')
        uses: dprint/check@v2.0

      - name: test
        run: deno test -A
